[build]
  command = "npm run build"
  publish = "out"

[functions]
  [functions.verify]
    src = "netlify/functions/verify.js"
    dest = ".netlify/functions/verify"

[dev]
  targetPort = 3000
  command = "npm run dev"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true